# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2pDEHT2Z-r4Q4HIABHtLScvD5HzhUXs
"""

pip install transformers torch gradio pypdf

import gradio as gr

# Replace these dummy functions with real logic
def eco_tips_generator(keywords):
    return f"Here are some eco tips based on your input: {keywords}"

def policy_summarization(pdf_file, policy_text):
    # For now, just return a dummy summary
    return "This is a summary of the uploaded or pasted policy document."

with gr.Blocks() as app:
    # Eco Tips Generator Section
    with gr.Row():
        with gr.Column():
            keywords_input = gr.Textbox(
                label="Environmental Problem / Keywords",
                placeholder="e.g., plastic, solar, water waste, energy saving...",
                lines=3
            )
            generate_tips_btn = gr.Button("Generate Eco Tips")

        with gr.Column():
            tips_output = gr.Textbox(
                label="Sustainable Living Tips",
                lines=15
            )

    generate_tips_btn.click(
        fn=eco_tips_generator,
        inputs=keywords_input,
        outputs=tips_output
    )

    # Policy Summarization Section
    with gr.TabItem("Policy Summarization"):
        with gr.Row():
            with gr.Column():
                pdf_upload = gr.File(
                    label="Upload Policy PDF",
                    file_types=[".pdf"]
                )
                policy_text_input = gr.Textbox(
                    label="Or paste policy text here",
                    placeholder="Paste policy document text...",
                    lines=5
                )
                summarize_btn = gr.Button("Summarize Policy")

            with gr.Column():
                summary_output = gr.Textbox(
                    label="Policy Summary & Key Points",
                    lines=20
                )

        summarize_btn.click(
            fn=policy_summarization,
            inputs=[pdf_upload, policy_text_input],
            outputs=summary_output
        )

# Launch the app
app.launch(share=True)